// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const mediaQueries = {
 "tabletMax": "1027px",
 "tabletMin": "768px",
 "mobileMax": "767px"
} as const;

export default mediaQueries;
